language: python
python:
- 3.8
- 3.7
- 3.6
before_install:
- pip install poetry
install: pip install -U tox-travis
script: tox
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: SpikingNeurons
  password:
    secure: gmLMg2WRSly3B37nRwdnvtmGWkQp+om+YjSW8xOCppM4d0CgH7gG25I8E+xxrjGLTnXoD7fIXkCiHoEs/jQ3ixTox3a6lVcF9QPCKO6iLouRFkj54JBck5V7Z+NGMFnhnt/Rz1eKSh/cyomw0tJzJ9IilEBSlpEk6/dEbyzmVoNN03I2q3jurnAooHb5DcMhdlYGvvJWyTZyuoI9trJbzgF5q+NrAVjm6iKpPoI/mciOutFDxwwQ/NJp6MUW0Kdf1Qqq4i/MqAuDIpH5kWTs5LZgdB5mMArPQxEh8iwe29sTTnPzDkKukZ6st+08+p2sxcgmcb4cmPqSv3m2Uc7P+uKFiMn2cQmPhFGsxlSQsht2XlnI0VvMJbCktj7bTlJnKDWIDQ/OVCnvg0AyCiC24yDT3+tojeUEr1UUXyMD7GPZFpTlH1+x8IW8AarnvdUlp7XRSQJ/yCrqfwqwJInv6+BLW50h+dyA/gZfx5BuwPO6iiMpuIJ3M+xjtrY62L7tIP6sNfKmyARinHwTJTPPiYSXIqLF8Irh0PQZb7L6+F2vYFkNAu0MG3KktczNjRbxS2LXtmBLPTlj7PzFQ+doYHbsAm38vVMEbj4NGepIOZkjlfeh4F6MxA0xKaqJ97vQFRo6OwVHpTjkCWVU0rO4lVdVbbAAv+vQhRNQA8GtQ3U=
  on:
    tags: true
    repo: SpikingNeurons/toolcraft
    python: 3.7
