
name: Python package

# Controls when the action will run. 
on:

  # Run this workflow when this tag is pushed
  push:
    tags:
      - 'v*.*.*'
      
  # Run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        python_version: '3.7'
        poetry_version: '==1.1.5'  # (PIP version specifier syntax)
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
        
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
